COMPONENT=EcolStationADAppC

CFLAGS += -I$(TOSDIR)/lib/net \
          -I$(TOSDIR)/lib/net/le \
          -I$(TOSDIR)/lib/net/ctp \
          -DTOSH_DATA_LENGTH=35 \
          -DCC2420_DEF_RFPOWER=11 \
          -DLOW_POWER_LISTENING

include $(MAKERULES)

